### ISSUE TITLE
Kedro in mode Yarn Cluster?

### ISSUE THREAD

**Issue by steevelaquitaine** [quantumblacklabs/kedro#529] opened 2020-09-28 15:18 UTC
## What I am trying to do
I am trying to run Kedro with spark with --master=yarn and --deploy-mode=cluster. 
Has anybody managed to make kedro run on a cluster with that configuration?
As far as I can see, the documentation does not provide information about that configuration.
Thanks in advance.

**Comment by Minyus** [comment] 2020-09-30 15:08
I asked basically the same question and got reply from @dataengineerone at:
https://discourse.kedro.community/t/any-examples-to-use-cluster-mode-of-spark-with-kedro/43

It seems we can include [configuration](https://spark.apache.org/docs/latest/configuration.html) at `spark.yml` like this:
```yaml
# spark.yml
spark.master: yarn
spark.submit.deployMode: cluster
```

This video explains about `spark.yml`:
https://youtu.be/vYBMpPZep6E?t=221

**Comment by 921kiyo** [comment] 2020-10-02 09:26
Closing this issue, but feel free to re-open it if you have any follow-up question :)

**Closed by 921kiyo** 2020-10-02 09:26 UTC
Labels: Issue: Question

**Comment by Fzmed** [comment] 2020-11-20 09:05
Hello @Minyus, @steevelaquitaine,
I've tested the reply by @dataengineerone and I can't make it work. 
It appears that spark in a yarn cluster mode is not supported in an interactive shell applications which is what happens when using spark.yml (it instantiate a SparkSession in the run ).  
( as you can read here  : https://www.informit.com/articles/article.aspx?p=2928186&seqNum=3 ) 

It might be necessary to change the kedro run in order to make it useful in a production environment (using yarn cluster). 
I haven't figured that yet, anybody gave it a try ? 
Best,

**Comment by steevelaquitaine** [comment] 2020-11-20 09:10
Hello @Minyus, @steevelaquitaine,

Yes I agree, the video helps implementing two patterns:

 --master local / deploy-mode client
 --master yarn / deploy-mode client

but not  the pattern desired in production --master yarn / deploy-mode cluster yet.

**Comment by ghifariram** [comment] 2021-02-04 05:15
Hello @Minyus,

I've tested with `spark.submit.deployMode: cluster` but got this error: `Cluster deploy mode is not applicable to Spark shells`.
I'm using `kedro v0.16.4`, any idea?

Best

**Comment by yurigba** [comment] 2022-02-11 18:01
The problem is that to use spark in cluster mode, you need to use `spark-submit`, not pyspark shell, which is what the kedro context uses.
