### ISSUE TITLE
<Title> use two kedro component on one page

### ISSUE THREAD

**Issue by deathelegy** [quantumblacklabs/kedro#698] opened 2021-02-25 11:48 UTC
## Description
As title, when I use one kedro on the web page, another one on modal, then close the modal.
The first one kedro will cause error, how can I use two Kedro component on the same page

**Comment by lorenabalan** [comment] 2021-02-25 11:58
Hi @deathelegy I'm not following what the issue is, could you please provide more details. Please also make sure you're raising the issue in the correct repo, "use kedro on web page" sounds more like kedro-viz to me.

**Comment by AntonyMilneQB** [comment] 2021-03-16 08:23
I'm going to close this issue, but please feel free to reopen if you'd like to add more details in the future 🙂

**Closed by AntonyMilneQB** 2021-03-16 08:23 UTC
Labels: Issue: Feature Request
