### ISSUE TITLE
kedro-docker plugin

### ISSUE THREAD

**Issue by agarwalsourabh55** [quantumblacklabs/kedro#768] opened 2021-05-19 10:15 UTC
## Description
Whenever I try to initialize kedro docker init then theri is always one error that comes 

## Context
How has this bug affected you? What were you trying to accomplish?

kedro.framework.cli.utils.KedroCliError: 
Cannot connect to the Docker daemon. Is the Docker daemon running?

Run with --verbose to see the full exception
Error: 
Cannot connect to the Docker daemon. Is the Docker daemon running?

i am using latest kedro version and have already install kedro docker and daemon is also running

**Comment by ignacioparicio** [comment] 2021-05-19 11:43
Hi @agarwalsourabh55, what output do you get when you do `docker run hello-world` in your terminal?

**Comment by agarwalsourabh55** [comment] 2021-05-19 11:49
> Hi @agarwalsourabh55, what output do you get when you do `docker run hello-world` in your terminal?
OUTPUT:->
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b8dfde127a29: Pull complete 
Digest: sha256:5122f6204b6a3596e048758cabba3c46b1c937a46b5be6225b835d091b90e46c
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by ignacioparicio** [comment] 2021-05-19 14:21
Thank you for the additional details. This seems to be an issue with the docker installation / communication between the docker daemon and API requests, and not really a bug in `kedro` or `kedro-airflow` as far as I can tell. I'm on a Windows machine and cannot reproduce the issue (both `kedro docker init` and `kedro docker build` work fine for me). 

If you haven't already, I would suggest to go over [this page](https://docs.docker.com/config/daemon/). `docker info` might also provide useful details.

---
My env:
* `kedro==0.17.3`
* `kedro-docker==0.2.2`
* Running docker on [Windows with Hyper-V backend](https://docs.docker.com/docker-for-windows/install/)

**Comment by ignacioparicio** [comment] 2021-05-19 16:40
@agarwalsourabh55 I will close the issue for now. If you still feel this is a bug on the `kedro` / `kedro-docker` side, please let me know and I will re-open it.

**Closed by ignacioparicio** 2021-05-19 16:40 UTC
Labels: Issue: Bug Report
