### ISSUE TITLE
[KED-2337] Broken dependencies in the latest kedro conda distribution (0.16.2)

### ISSUE THREAD

**Issue by Sitin** [quantumblacklabs/kedro#636] opened 2020-12-08 11:53 UTC
## Description
Broken dependencies in the latest conda distribution (0.16.2).

Probably the problem is in `jupyter_client>=5.1.0, <6.0`.

At the same environment the latest pip distribution 0.16.6 works fine.

## Context
Impossible to instal project dependencies.

## Steps to Reproduce

Install Kedro into a fresh conda environment and create a test project:
```sh
conda create --name kedro python=3.7
conda activate kedro
conda install -c conda-forge kedro
kedro -V   # kedro, version 0.16.2

mkdir -p /tmp/kedro
cd /tmp/kedro

kedro new  # setting Test, test, test, no example project
cd test
```

Dependencies from `cat src/requirements.txt`:
```
black==v19.10b0
flake8>=3.7.9, <4.0
ipython>=7.0.0, <8.0
isort>=4.3.21, <5.0
jupyter>=1.0.0, <2.0
jupyter_client>=5.1.0, <6.0
jupyterlab==0.31.1
kedro==0.16.2
nbstripout==0.3.3
pytest-cov>=2.5, <3.0
pytest-mock>=1.7.1,<2.0
pytest>=5.0, <6.0
wheel==0.32.2
```

Attempt to install dependencies:
```sh
kedro install
```

## Expected Result
Kedro should install default project dependencies

## Actual Result
Kedro can't resolve dependencies and fails after `kedro install`:

```
No requirements.in found. Copying contents from requirements.txt...
/usr/local/Caskroom/miniconda/base/envs/kedro/bin/python3.7 -m piptools compile -q /private/tmp/kedro/test/src/requirements.in
Could not find a version that matches jupyter_client<6.0,>=4.1,>=5.1.0,>=5.3.4,>=6.1.5 (from -r /private/tmp/kedro/test/src/requirements.in (line 6))
Tried: 4.0.0, 4.0.0, 4.0.0, 4.1.0, 4.1.0, 4.1.1, 4.1.1, 4.1.1, 4.2.0, 4.2.0, 4.2.0, 4.2.1, 4.2.1, 4.2.1, 4.2.2, 4.2.2, 4.2.2, 4.3.0, 4.3.0, 4.3.0, 4.4.0, 4.4.0, 5.0.0, 5.0.0, 5.0.1, 5.0.1, 5.1.0, 5.1.0, 5.2.0, 5.2.0, 5.2.1, 5.2.1, 5.2.2, 5.2.2, 5.2.3, 5.2.3, 5.2.4, 5.2.4, 5.3.0, 5.3.0, 5.3.1, 5.3.1, 5.3.2, 5.3.2, 5.3.3, 5.3.3, 5.3.4, 5.3.4, 5.3.5, 5.3.5, 6.0.0, 6.0.0, 6.1.0, 6.1.0, 6.1.1, 6.1.1, 6.1.2, 6.1.2, 6.1.3, 6.1.3, 6.1.5, 6.1.5, 6.1.6, 6.1.6, 6.1.7, 6.1.7
There are incompatible versions in the resolved dependencies:
  jupyter_client<6.0,>=5.1.0 (from -r /private/tmp/kedro/test/src/requirements.in (line 6))
  jupyter-client>=6.1.5 (from nbclient==0.5.1->nbconvert==6.0.7->jupyter==1.0.0->-r /private/tmp/kedro/test/src/requirements.in (line 5))
  jupyter-client (from jupyter-console==6.2.0->jupyter==1.0.0->-r /private/tmp/kedro/test/src/requirements.in (line 5))
  jupyter-client>=4.1 (from qtconsole==5.0.1->jupyter==1.0.0->-r /private/tmp/kedro/test/src/requirements.in (line 5))
  jupyter-client>=5.3.4 (from notebook==6.1.5->jupyter==1.0.0->-r /private/tmp/kedro/test/src/requirements.in (line 5))
  jupyter-client<6.0,>=5.1.0 (from kedro==0.16.2->-r /private/tmp/kedro/test/src/requirements.in (line 8))
  jupyter-client (from ipykernel==5.3.4->jupyter==1.0.0->-r /private/tmp/kedro/test/src/requirements.in (line 5))
```

From `cat src/requirements.in`:

```
black==v19.10b0
flake8>=3.7.9, <4.0
ipython>=7.0.0, <8.0
isort>=4.3.21, <5.0
jupyter>=1.0.0, <2.0
jupyter_client>=5.1.0, <6.0
jupyterlab==0.31.1
kedro==0.16.2
nbstripout==0.3.3
pytest-cov>=2.5, <3.0
pytest-mock>=1.7.1,<2.0
pytest>=5.0, <6.0
wheel==0.32.2
```

## Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.16.2
* Python version used (`python -V`): Python 3.7.8
* Operating system and version: macOS Catalina 10.15.5

**Comment by DmitriiDeriabinQB** [comment] 2020-12-08 14:59
Thank you for the report @Sitin. I can confirm that this is indeed an issue with Kedro 0.16.2 and `kedro build-reqs` cannot reliably resolve the package versions anymore for newly created project. The issue is reproducible with Kedro installed via pip too (`pip install "kedro==0.16.2"`).

The cause of the issue in version 0.16.2 is the fact that Kedro package itself has a requirement for `jupyter_client>=5.1.0, <6.0` which stops pip-compile from finding a satisfying version for it (as other packages require `jupyter-client>=6.1.5`).

The suggested solution would be to use the latest version - Kedro 0.16.6, which is backwards compatible with 0.16.2. The requirement for jupyter client in the latest Kedro is wider: `jupyter_client>=5.1, <7.0`, so it doesn't break the compilation.

Kedro 0.16.6 is [visible on `conda-forge`](https://anaconda.org/conda-forge/kedro), however when calling `conda install -c conda-forge kedro`, it still tries to install 0.16.2. If you can fall back to pip, then you can simply run `pip install "kedro==0.16.6"` in your environment.

If you cannot upgrade Kedro, as a workaround you can add `nbconvert<6.0` in your requirements, which should hopefully make pip-compile happy again.

**Comment by Sitin** [comment] 2020-12-08 19:58
Thank you, @DmitriiDeriabinQB for the advice. Since you are not install dependencies by conda anyway I will go with pip.

**Comment by lorenabalan** [comment] 2021-01-12 14:25
`conda install -c conda-forge kedro==0.16.6` would also work. We haven't yet figured out conda doesn't fetch the latest kedro version, but that is out of scope here. Will go ahead and close this issue as resolved.

**Closed by lorenabalan** 2021-01-12 14:25 UTC
Labels: Issue: Bug Report
