### ISSUE TITLE
Kedro viz

### ISSUE THREAD

**Issue by talk21991** [quantumblacklabs/kedro#168] opened 2019-11-20 19:55 UTC
When I was running `kedro viz` in my command prompt I got following error.

`NameError: name 'node' is not defined`

How to deal with this issue?

**Comment by tolomea** [comment] 2019-11-21 09:43
could you please run 'kedro info' and paste the output here

**Comment by tolomea** [comment] 2019-11-21 09:44
Also the full output of running `kedro viz`

**Comment by lorenabalan** [comment] 2019-12-02 18:08
Hi @talk21991 , in order to debug this we need more information. Could you please follow the steps mentioned above by @tolomea ?

**Comment by talk21991** [comment] 2019-12-03 18:41
Hi,

Sorry for the late reply. I able to understand my fault to define pipeline.

Actually I was skipping calling node( from kedro.node import nodename) in
my code when I am defining Pipeline. Now kedro viz is working. Thank.

**Comment by mzjp2** [comment] 2019-12-04 00:53
> Hi, Sorry for the late reply. I able to understand my fault to define pipeline. Actually I was skipping calling node( from kedro.node import nodename) in my code when I am defining Pipeline. Now kedro viz is working. Thank.
> […](#)

If the issue is resolved, you might consider closing the issue 🙂

**Comment by lorenabalan** [comment] 2019-12-04 09:33
Thanks @talk21991 , glad to hear it's working! I'll go ahead and close this issue.

**Closed by lorenabalan** 2019-12-04 09:33 UTC
Labels: Issue: Bug Report

**Comment by talk21991** [comment] 2019-12-04 10:04
Hi,

Many thanks.

With regards
Arpan
