### ISSUE TITLE
custom project context class

### ISSUE THREAD

**Issue by nagendratekuri** [quantumblacklabs/kedro#676] opened 2021-01-21 15:52 UTC
## Description
I would like to use centralized Spark configuration file under conf/base/spark.yml and would like to pass these to SparkSession.

## Context
I followed the steps mentioned here in the documentation.
https://kedro.readthedocs.io/en/stable/11_tools_integration/01_pyspark.html?highlight=SparkSession#initialise-a-sparksession-in-custom-project-context-class

First Issue: KedroContext
Which is not imported in the given example.

Second Issue:
If I import like this 
from kedro.framework.context import KedroContext
I am getting the below error:
TypeError: __init__() got an unexpected keyword argument 'package_name'

```
File "/root/user_files/envs/xpvu4/lib/python3.7/site-packages/kedro/framework/session/session.py", line 226, in create
    session._setup_logging()
  File "/root/user_files/envs/xpvu4/lib/python3.7/site-packages/kedro/framework/session/session.py", line 244, in _setup_logging
    conf_logging = self._get_logging_config()
  File "/root/user_files/envs/xpvu4/lib/python3.7/site-packages/kedro/framework/session/session.py", line 230, in _get_logging_config
    context = self.load_context()
  File "/root/user_files/envs/xpvu4/lib/python3.7/site-packages/kedro/framework/session/session.py", line 306, in load_context
    extra_params=extra_params,
TypeError: __init__() got an unexpected keyword argument 'package_name'

```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.17.0
* Python version used (`python -V`): Python 3.7.9
* Operating system and version:

**Comment by MerelTheisenQB** [comment] 2021-01-22 14:52
Hi @nagendratekuri, thanks for reporting this issue! Could you provide steps to reproduce the problem you're seeing? Thanks!

**Comment by remiromi** [comment] 2021-02-09 07:47
Hello! I am having the same issue. I am trying to add Spark communication to a functioning kedro pipeline.
**Versions:** Kedro 0.17.0, Python 3.6.8

Here is what I did:
### Settings.py
```
from my_project.project_context import CustomContext
CONTEXT_CLASS = CustomContext
```
### project_context.py
```
class CustomContext(KedroContext):

    def __init__(self, project_path: Union[Path, str], env: str = None, extra_params: Dict[str, Any] = None, ):
        super().__init__(project_path, env, extra_params)
        self.init_spark_session()

    def init_spark_session(self) -> None:
        """Initialises a SparkSession using the config defined in project's conf folder."""

        # Load the spark configuration in spark.yaml using the config loader
        parameters = self.config_loader.get("spark*", "spark*/**")
        spark_conf = SparkConf().setAll(parameters.items())

        # Initialise the spark session 
        spark_session_conf = (
            SparkSession.builder
            .appName(self.project_name)
            .enableHiveSupport()
            .config(conf=spark_conf)
        )
        _spark_session = spark_session_conf.getOrCreate()
        _spark_session.sparkContext.setLogLevel("WARN")
```

### conf/base/spark.yml 
```
## Spark Configs ##
spark.driver.maxResultSize: 3g
spark.scheduler.mode: FAIR
```

Then, I created a small test node:
```
def fake_node(param):
    SparkSession.builder.getOrCreate()
    return f"param is {param}"
```

## Error
```
2021-02-08 17:17:07,523 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
Traceback (most recent call last):
  File "C:\Python\Python36\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python\Python36\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python\Python36\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\Python36\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\remigio\Python\cross-sell\my_project\src\my_project\cli.py", line 227, in run
    with KedroSession.create(package_name, env=env, extra_params=params) as session:
  File "C:\Python\Python36\lib\site-packages\kedro\framework\session\session.py", line 226, in create
    session._setup_logging()
  File "C:\Python\Python36\lib\site-packages\kedro\framework\session\session.py", line 244, in _setup_logging
    conf_logging = self._get_logging_config()
  File "C:\Python\Python36\lib\site-packages\kedro\framework\session\session.py", line 230, in _get_logging_config
    context = self.load_context()
  File "C:\Python\Python36\lib\site-packages\kedro\framework\session\session.py", line 306, in load_context
    extra_params=extra_params,
TypeError: __init__() got an unexpected keyword argument 'package_name'

Process finished with exit code -1

```

**Comment by samhiscoxqb** [comment] 2021-02-09 12:26
Hello! The example `CustomContext` needs a little tweak to include `project_name` as an `__init__` argument:

```Python
from typing import Any, Dict, Union
from pathlib import Path

from pyspark import SparkConf
from pyspark.sql import SparkSession

from kedro.framework.context import KedroContext


class CustomContext(KedroContext):

    def __init__(
        self,
        package_name: str,                                                 # <= Add package_name here
        project_path: Union[Path, str],
        env: str = None,
        extra_params: Dict[str, Any] = None,
    ):
        super().__init__(package_name, project_path, env, extra_params).   # <= and here!
        self.init_spark_session()

    def init_spark_session(self) -> None:
        """Initialises a SparkSession using the config defined in project's conf folder."""

        # Load the spark configuration in spark.yaml using the config loader
        parameters = self.config_loader.get("spark*", "spark*/**")
        spark_conf = SparkConf().setAll(parameters.items())

        # Initialise the spark session
        spark_session_conf = (
            SparkSession.builder
            .appName(self.package_name)
            .enableHiveSupport()
            .config(conf=spark_conf)
        )
        _spark_session = spark_session_conf.getOrCreate()
        _spark_session.sparkContext.setLogLevel("WARN")
```

I'll open a PR to update this - thanks for raising both 👍

**Comment by remiromi** [comment] 2021-02-10 14:14
@samhiscoxqb thanks a lot for your help, it worked! I had also to edit another line that you wrote correctly but in the doc is not (-> https://kedro.readthedocs.io/en/stable/11_tools_integration/01_pyspark.html )
In the doc the code is 

```python
# Initialise the spark session
        spark_session_conf = (
            SparkSession.builder
            .appName(self.project_name)      # Error Here
            .enableHiveSupport()
            .config(conf=spark_conf)
        )
```

While I had to edit the appName line as

```python
# Initialise the spark session
        spark_session_conf = (
            SparkSession.builder
            .appName(self.package_name)        # Corrected line
            .enableHiveSupport()
            .config(conf=spark_conf)
        )
```

since it was giving me AttributeError on the **self.project_name** call.

Thanks again!

**Comment by lorenabalan** [comment] 2021-02-26 09:27
Thank you all, I'll close this as resolved. @samhiscoxqb 's [PR](https://github.com/quantumblacklabs/kedro/pull/690) has also been merged.

**Closed by lorenabalan** 2021-02-26 09:27 UTC
Labels: Issue: Bug Report
