### ISSUE TITLE
TypeError on Spaceflight Tutorial from hooks.py

### ISSUE THREAD

**Issue by beatgeek** [quantumblacklabs/kedro#626] opened 2020-11-28 22:27 UTC
## Description
Following along the de and ds pipeline creation. From this point in the tutorial: from [Data Science pipeline](https://kedro.readthedocs.io/en/stable/03_tutorial/04_create_pipelines.html#data-science-pipeline), on `kedro run` I am getting a `TypeError: can only concatenate tuple (not "Pipeline") to tuple`. 
## Context
Running through the tutorial. 

## Steps to Reproduce
1. Following the tutorial steps for additions to `hooks.py`, `nodes.py` and `pipeline.py` for `src/kedro_tutorial/pipelines/data_science/ and `src/kedro_tutorial/` for hooks
2. `kedro run`

## Expected Result
```
kedro run

2019-08-19 10:51:46,501 - root - INFO - ** Kedro project kedro-tutorial
2019-08-19 10:51:46,510 - kedro.io.data_catalog - INFO - Loading data from `companies` (CSVDataSet)...
2019-08-19 10:51:46,547 - kedro.pipeline.node - INFO - Running node: preprocessing_companies: preprocess_companies([companies]) -> [preprocessed_companies]
2019-08-19 10:51:46,597 - kedro.io.data_catalog - INFO - Saving data to `preprocessed_companies` (CSVDataSet)...
2019-08-19 10:51:46,906 - kedro.runner.sequential_runner - INFO - Completed 1 out of 6 tasks
2019-08-19 10:51:46,906 - kedro.io.data_catalog - INFO - Loading data from `shuttles` (ExcelDataSet)...
2019-08-19 10:51:55,324 - kedro.pipeline.node - INFO - Running node: preprocessing_shuttles: preprocess_shuttles([shuttles]) -> [preprocessed_shuttles]
2019-08-19 10:51:55,389 - kedro.io.data_catalog - INFO - Saving data to `preprocessed_shuttles` (CSVDataSet)...
2019-08-19 10:51:55,932 - kedro.runner.sequential_runner - INFO - Completed 2 out of 6 tasks
2019-08-19 10:51:55,932 - kedro.io.data_catalog - INFO - Loading data from `preprocessed_shuttles` (CSVDataSet)...
2019-08-19 10:51:56,042 - kedro.io.data_catalog - INFO - Loading data from `preprocessed_companies` (CSVDataSet)...
2019-08-19 10:51:56,078 - kedro.io.data_catalog - INFO - Loading data from `reviews` (CSVDataSet)...
2019-08-19 10:51:56,139 - kedro.pipeline.node - INFO - Running node: create_master_table([preprocessed_companies,preprocessed_shuttles,reviews]) -> [master_table]
2019-08-19 10:51:58,037 - kedro.io.data_catalog - INFO - Saving data to `master_table` (CSVDataSet)...
2019-08-19 10:52:09,133 - kedro.runner.sequential_runner - INFO - Completed 3 out of 6 tasks
2019-08-19 10:52:09,133 - kedro.io.data_catalog - INFO - Loading data from `master_table` (CSVDataSet)...
2019-08-19 10:52:10,941 - kedro.io.data_catalog - INFO - Loading data from `parameters` (MemoryDataSet)...
2019-08-19 10:52:10,941 - kedro.pipeline.node - INFO - Running node: split_data([master_table,parameters]) -> [X_test,X_train,y_test,y_train]
2019-08-19 10:52:11,343 - kedro.io.data_catalog - INFO - Saving data to `X_train` (MemoryDataSet)...
2019-08-19 10:52:11,372 - kedro.io.data_catalog - INFO - Saving data to `X_test` (MemoryDataSet)...
2019-08-19 10:52:11,380 - kedro.io.data_catalog - INFO - Saving data to `y_train` (MemoryDataSet)...
2019-08-19 10:52:11,381 - kedro.io.data_catalog - INFO - Saving data to `y_test` (MemoryDataSet)...
2019-08-19 10:52:11,443 - kedro.runner.sequential_runner - INFO - Completed 4 out of 6 tasks
2019-08-19 10:52:11,443 - kedro.io.data_catalog - INFO - Loading data from `X_train` (MemoryDataSet)...
2019-08-19 10:52:11,472 - kedro.io.data_catalog - INFO - Loading data from `y_train` (MemoryDataSet)...
2019-08-19 10:52:11,474 - kedro.pipeline.node - INFO - Running node: train_model([X_train,y_train]) -> [regressor]
2019-08-19 10:52:11,704 - kedro.io.data_catalog - INFO - Saving data to `regressor` (PickleDataSet)...
2019-08-19 10:52:11,776 - kedro.runner.sequential_runner - INFO - Completed 5 out of 6 tasks
2019-08-19 10:52:11,776 - kedro.io.data_catalog - INFO - Loading data from `regressor` (PickleDataSet)...
2019-08-19 10:52:11,776 - kedro.io.data_catalog - INFO - Loading data from `X_test` (MemoryDataSet)...
2019-08-19 10:52:11,784 - kedro.io.data_catalog - INFO - Loading data from `y_test` (MemoryDataSet)...
2019-08-19 10:52:11,785 - kedro.pipeline.node - INFO - Running node: evaluate_model([X_test,regressor,y_test]) -> None
2019-08-19 10:52:11,830 - kedro_tutorial.nodes.price_prediction - INFO - Model has a coefficient R^2 of 0.456.
2019-08-19 10:52:11,869 - kedro.runner.sequential_runner - INFO - Completed 6 out of 6 tasks
2019-08-19 10:52:11,869 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
```

## Actual Result

```
kedro run
2020-11-27 17:30:57,451 - root - INFO - ** Kedro project kedro-space
Traceback (most recent call last):
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 725, in main
    cli_collection()
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/aleary/amlg-code/kedro/kedro-space/kedro_cli.py", line 234, in run
    pipeline_name=pipeline,
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 718, in run
    pipeline = self._get_pipeline(name=pipeline_name)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 381, in _get_pipeline
    pipelines = self._get_pipelines()
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 400, in _get_pipelines
    hook_manager.hook.register_pipelines()  # pylint: disable=no-member
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/aleary/amlg-code/kedro/kedro-space/src/kedro_space/hooks.py", line 56, in register_pipelines
    "__default__": de_pipeline + ds_pipeline,
```

```
kedro run --pipeline=de
2020-11-28 14:23:11,065 - root - INFO - ** Kedro project kedro-space
Traceback (most recent call last):
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 725, in main
    cli_collection()
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/aleary/amlg-code/kedro/kedro-space/kedro_cli.py", line 234, in run
    pipeline_name=pipeline,
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 718, in run
    pipeline = self._get_pipeline(name=pipeline_name)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 381, in _get_pipeline
    pipelines = self._get_pipelines()
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/kedro/framework/context/context.py", line 400, in _get_pipelines
    hook_manager.hook.register_pipelines()  # pylint: disable=no-member
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/aleary/.pyenv/versions/3.7.3/envs/kedro-env/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/aleary/amlg-code/kedro/kedro-space/src/kedro_space/hooks.py", line 56, in register_pipelines
    "__default__": de_pipeline + ds_pipeline,
TypeError: can only concatenate tuple (not "Pipeline") to tuple
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:
* Kedro version used (`pip show kedro` or `kedro -V`): `kedro, version 0.16.6`
* Python version used (`python -V`): `Python 3.7.3` using pyenv virtualenv
* Operating system and version: MacOS Catalina version 10.15.17

**Comment by beatgeek** [comment] 2020-11-29 00:38
Realizing this is from my pyenv virtualenv is actually ok. I checked by also loading the tutorial starter and it ran successfully.
I see the tutorial docs want you to add to `hooks.py` in one way, but I was able to resolve with:

```
data_engineering_pipeline = de.create_pipeline()
        data_science_pipeline = ds.create_pipeline()

        return {
            "__default__": data_engineering_pipeline + data_science_pipeline,
            "de": data_engineering_pipeline,
            "ds": data_science_pipeline,
        }
```

**Comment by yetudada** [comment] 2020-11-30 11:07
Hi @beatgeek! Thank you for flagging this. I have some follow-up questions:  
- Does this error only happen when you try and add the data science pipeline? 
- And you mentioned that you were able to resolve this issue by adding appending `hooks.py`, how did you try add the pipeline in the first place?

**Comment by beatgeek** [comment] 2020-11-30 21:38
Hi @yetudada!
Thanks for your questions and here are some more details:
* I had a TypeError regarding Tuple for Pipeline with the ds pipeline. Using the tutorial code. It could be my error in following the tutorial. Without the reference to create_pipeline() I saw TypeErrors. I did see runs with the DE component. 
* I added the pipeline by following the updates to node and then the hooks in the tutorial. I would see errors from the register_pipeline: `def register_pipelines(self) -> Dict[str, Pipeline]:` as if it's not finding the Class. 
* I tried `kedro run`. 
* I'm using a pyenv virtualenv where the python environment is conda 3.8.

**Comment by lorenabalan** [comment] 2021-01-12 14:22
Glad you it figured out @beatgeek . 

> Realizing this is from my pyenv virtualenv is actually ok. I checked by also loading the tutorial starter and it ran successfully.
> I see the tutorial docs want you to add to `hooks.py` in one way, but I was able to resolve with:
> 
> ```
> data_engineering_pipeline = de.create_pipeline()
>         data_science_pipeline = ds.create_pipeline()
> 
>         return {
>             "__default__": data_engineering_pipeline + data_science_pipeline,
>             "de": data_engineering_pipeline,
>             "ds": data_science_pipeline,
>         }
> ```

I'm not sure what the difference is but that's exactly what was meant to be written. See https://kedro.readthedocs.io/en/stable/03_tutorial/04_create_pipelines.html#id2 

I didn't fully understand what was happening before, I was not able to reproduce so it might've just been a typo/mistake when following the tutorial. Closing this issue as resolved.

**Closed by lorenabalan** 2021-01-12 14:22 UTC
Labels: Issue: Bug Report
