### ISSUE TITLE
String as an argument to the node in pipeline.

### ISSUE THREAD

**Issue by parulML** [quantumblacklabs/kedro#213] opened 2020-02-05 08:49 UTC
I want to add feature engineering in the pipeline for every feature and for that I want to pass a string as an argument to the function inside the node but that's not allowed in kedro yet and I get following error:-
`ValueError: Pipeline input(s) {"xxxx","yyyy"} not found in the DataCatalog`
So I want to know if there's a way to use string as in argument inside node.

Thanks in advance.

**Comment by lorenabalan** [comment] 2020-02-05 09:38
Hi @parulML, you might find this answer helpful: https://stackoverflow.com/questions/58875820/how-to-pass-a-literal-value-to-a-node 
If you replace the given example (integer 1), with a string, then you have exactly your case.

**Comment by parulML** [comment] 2020-02-06 08:38
Thanks, @lorenabalan I did what you suggested but I get below error:-
`AttributeError: 'str' object has no attribute 'items'`

This is the code snipped:-
`    create_feature_engineering_pipeline = Pipeline([
        node(partial(FeatureEngineering.date_features, column_name='DateKey'),
             inputs=['merged_files'],
             outputs=None,
             name="date_features_for_datekey"
             ),
], name='create_feature_engineering_pipeline')`

**Comment by lorenabalan** [comment] 2020-02-06 10:31
I'm afraid we can't debug without knowing what the actual node function looks like, and a full stack trace. Your pipeline definition looks fine to me, my feeling is the problem is within the function, not with Kedro itself.

**Comment by yetudada** [comment] 2020-04-15 11:45
Hey @parulML, were you able to get some help with this? 😄  Do let us know, otherwise we'll be closing this ticket.

**Comment by yetudada** [comment] 2020-05-20 10:24
Hi @parulML, I hope that you managed to get assistance on this. Let us know if you need anything else. I'll be closing this issue. If you are still stuck then just comment on it and we'll reopen it, or you can create a new issue if you have any more feedback or queries.

**Closed by yetudada** 2020-05-20 10:24 UTC
Labels: Issue: Feature Request

**Comment by sansagara** [comment] 2020-09-25 13:36
I think kedro should add the way to pass a literal to a node, just like they did with `param:`.
Maybe something like literal: or string: and int:

**Comment by WaylonWalker** [comment] 2020-09-26 15:22
Currently kedro only supports passing parameters or catalog entries to nodes.  The way that you would pass other options in would be with a partial or a lambda.  I most often use lambdas, you can look up how to do it with functools.partial if you would rather use that.

```
def my_func(data, param):
   data[feature] = param
   return data

node(
   func= lambda data: my_func(data, 'xxx')
   ...
)

node(
   func= lambda data: my_func(data, 'yyy')
   ...
)
```

I often generate nodes dynamically, be careful to bind your inputs to your lambdas if you create them in a loop.  More on that in this article https://waylonwalker.com/blog/bind-dynamic-lambdas.

**Comment by sansagara** [comment] 2020-09-26 16:43
Thats a nice suggestion, i must say.
