### ISSUE TITLE
conditional evaluation of nodes / sub-pipelines

### ISSUE THREAD

**Issue by bonnevm** [quantumblacklabs/kedro#104] opened 2019-09-25 21:52 UTC
## Description
Is there a way to declare a pipeline that contains nodes (sub-pipelines) that are only evaluated based on the value of a predicate?

## Possible Implementation
 Here's conceptually what I would like to achieve:

`node_if` executes `pipeline_a` if the predicate is true and `pipeline_b` otherwise.

```python
def condition(val):
    return val < 10


def do_a1(val):
    return f"a1-{val}"

def do_a2(val):
    return f"a2-{val}"


def do_b(val):
    return f"b-{val}"

pipeline_a = Pipeline([
    node(func=do_a1, inputs=['val'], outputs='val_a1', name='do_a1'),
    node(func=do_a2, inputs=['val_a1'], outputs='val_a2', name='do_a2')
])

pipeline_b = Pipeline([
    node(func=do_b, inputs=['val'], outputs='val_b', name='do_b'),
])

pipeline = Pipeline([
    node_if(func=condition, inputs=['val'], branch_true=pipeline_a, branch_false=pipeline_b),
])
```
## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by DmitriiDeriabinQB** [comment] 2019-09-26 08:10
@bonnevm, thank you for raising this. For this use case we'd recommend to build the 'master' pipeline dynamically based on the condition. For example:
```python
pipeline_a = Pipeline([
    node(func=do_a1, inputs=['val'], outputs='val_a1', name='do_a1'),
    node(func=do_a2, inputs=['val_a1'], outputs='val_a2', name='do_a2')
])

pipeline_b = Pipeline([
    node(func=do_b, inputs=['val'], outputs='val_b', name='do_b'),
])

pipeline = Pipeline([pipeline_a if condition else pipeline_b])
```
This, however, implies that the condition must be evaluated at the very beginning of a run and cannot be produced as part of the pipeline.

**Comment by khdlim** [comment] 2019-10-02 07:46
Hi, I ran into a related issue as well. For example, I might want to construct a conditional (partial) pipeline based on some variables in parameters.yml. One example is "params:dataset_name", if I want to run different preprocessing pipelines for different datasets and feed them into a common modeling pipeline in a single kedro project.

There are a few options I considered:

Option 1: create a whole new project for different datasets, which would not be able to leverage common modeling pipeline code.

Option 2: Combine all the preprocessing into a single node and pass in "params:dataset_name" from parameters.yml, or add "params:dataset_name" as an input to every node.

Option 3: tag each pipeline seperately, in which case the user will have to manually add the --tag arguments in "kedro run". The complexity of this grows rather fast if you want a pipeline dependent on other variables as well in parameters.yml affecting different nodes in the pipeline. I would rather have a simple "--env=dataset1/expt1" for this.

I am wondering if you have any suggestions on alternative approaches? Currently, I have modified run.py to pass in ProjectContext.io as a keyword argument to pipeline.py so I can directly access parameters.yml keys in create_pipeline().

**Comment by DmitriiDeriabinQB** [comment] 2019-10-02 08:23
@khdlim for your use case there is indeed `--env` option in `kedro run` command. By default, Kedro pulls the catalog configuration from 2 locations: `conf/base` and `conf/local`. You can create another path `conf/expt1` and put additional configuration there. 

For example, you may have an entry for the dataset called `dataset1` in both `conf/base/catalog.yml` and `conf/expt1/catalog.yml`. Then if you run `kedro run --env=expt1`, the catalog from `conf/expt1/catalog.yml` will override the one from base. Please let us know if it's applicable for your use case. More information on config environments is available [here](https://kedro.readthedocs.io/en/latest/04_user_guide/03_configuration.html).

Another option would be to use a new [config templating feature](https://github.com/quantumblacklabs/private-kedro/blob/develop/kedro/contrib/config/templated_config.py) - this hasn't been released to PyPi yet, so you'd need to install Kedro from source. It would allow to parametrise your catalog based on some external data.

**Comment by khdlim** [comment] 2019-10-02 09:19
@DmitriiDeriabinQB Thanks for your reply. Indeed, I have been using the --env feature with kedro run and I love it. I have been using some self-implemented variants of this idea but this is much neater.

Unfortunately, it doesn't seem that create_pipeline has access to the DataCatalog by default, hence I have currently hacked it in run.py to add the DataCatalog as a keyword argument in create_pipeline. I was wondering if that was by design and if there is another way I can access the DataCatalog of the current ProjectContext directly from pipeline.py?

**Comment by Flid** [comment] 2019-10-04 09:42
Hi @khdlim 
We consider all the files created by `kedro new` in the project directory editable by users. If you need the catalog in the pipeline - pass it from `run.py`. Indeed that's a standard way.

**Comment by khdlim** [comment] 2019-10-08 17:13
@Flid 

Thanks for the reply. 

One issue I have noticed with modifying create_pipeline to take in DataCatalog is it breaks kedro-viz because the create_pipeline call in server.py in site-packages/kedro_viz calls create_pipeline with no arguments.

I have locally modified that part to pass in the same DataCatalog as well to visualize my pipeline (kedro-viz only allows to use /conf/base without an --env option, but that's a separate issue) but I was wondering if the user was not designed to pass arguments to create_pipeline to begin with.

I also saw you mention in [another post](https://github.com/quantumblacklabs/kedro/issues/105#issuecomment-538900792)that separate pipelines would be available soon, that would be a godsend as I would like to have different pipelines for evaluation, hyperparameter tuning etc and am currently hacking something ugly together. Looking forward to it!

**Comment by lorenabalan** [comment] 2019-10-09 08:50
HI @khdlim, thank you for sharing your experience, this is invaluable feedback!! Please see my inline responses, hoping they make sense to you. Feel free to reach out otherwise!

> kedro-viz only allows to use /conf/base without an --env option, but that's a separate issue 

That's a good point and I believe it has been raised before. We're in the process of rethinking and improving the experience of `KedroContext` / `ProjectContext` and we'll be sure to include this type of arguments in the discussion.

> but I was wondering if the user was not designed to pass arguments to create_pipeline to begin with.

That is the right question to ask. If you look at the [architecture diagram](https://kedro.readthedocs.io/en/latest/06_resources/02_architecture_overview.html) you can see that ``Pipeline`` and ``DataCatalog`` don't know about each other. You do have access to the catalog inside `create_pipeline`, as it's a property on the `KedroContext` class. While you can access it to get some information, we *don't* recommend mutating it - weird things might happen as a result.

> I also saw you mention in [another post](https://github.com/quantumblacklabs/kedro/issues/105#issuecomment-538900792) that separate pipelines would be available soon, that would be a godsend

You are in luck! We released version `0.15.2` yesterday, fetch it while it's hot. :) You check out a summary of the introduced changes [here](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md).

**Comment by khdlim** [comment] 2019-10-09 15:20
> You are in luck! We released version `0.15.2` yesterday, fetch it while it's hot. :) You can check out a summary of the introduced changes [here](https://github.com/quantumblacklabs/kedro/blob/master/RELEASE.md).

Yes I actually spent today using the new --pipeline tag and it is great!

> That is the right question to ask. If you look at the [architecture diagram](https://kedro.readthedocs.io/en/latest/06_resources/02_architecture_overview.html) you can see that `Pipeline` and `DataCatalog` don't know about each other. You do have access to the catalog inside `create_pipeline`, as it's a property on the `KedroContext` class. While you can access it to get some information, we _don't_ recommend mutating it - weird things might happen as a result.

Previously I was using some entries in parameters.yml to create conditional pipelines but I think the the latest release it's no longer necessary.

Incidentally, how do you recommend upgrading a project from 15.1 to 15.2? I upgraded the package, then started a new project with the same name (in a different directory) with kedro new and manually merged the files. Not sure if there is a better way?

**Comment by lorenabalan** [comment] 2019-10-11 14:19
I am closing this issue as answered, but please feel free to open a new one if there's a need for further clarification. :)

**Closed by lorenabalan** 2019-10-11 14:19 UTC
Labels: Issue: Feature Request

**Comment by Blacks7566** [comment] 2023-05-12 11:28
> @bonnevm, thank you for raising this. For this use case we'd recommend to build the 'master' pipeline dynamically based on the condition. For example:
> 
> ```python
> pipeline_a = Pipeline([
>     node(func=do_a1, inputs=['val'], outputs='val_a1', name='do_a1'),
>     node(func=do_a2, inputs=['val_a1'], outputs='val_a2', name='do_a2')
> ])
> 
> pipeline_b = Pipeline([
>     node(func=do_b, inputs=['val'], outputs='val_b', name='do_b'),
> ])
> 
> pipeline = Pipeline([pipeline_a if condition else pipeline_b])
> ```
> 
> This, however, implies that the condition must be evaluated at the very beginning of a run and cannot be produced as part of the pipeline.

# how can we pass the input for condition fun

**Comment by astrojuanlu** [comment] 2023-05-12 11:33
hi @Blacks7566, thank you for your interest in Kedro! please open a new issue with your question or send it to our Slack community: https://slack.kedro.org see you there!
