### ISSUE TITLE
No Journal if pipeline is run through the session

### ISSUE THREAD

**Issue by FlorianGD** [quantumblacklabs/kedro#757] opened 2021-04-29 13:36 UTC
## Description
When running a pipeline with `session.run()`, no entry is added in the journal. If the pipeline is run with `context.run()` an entry is added, but there is a warning that this method is going to be deprecated.  
It also seems that `kedro run` in the console does not add an entry in the journal also.

## Context
We have a visualisation for the past runs. We saw the deprecation warning, so I updated the code to use a session, but since then, no more entries.

## Steps to Reproduce
Within `kedro ipython`:
```python
>>> from pathlib import Path
>>> journal_path = context.config_loader.get("logging.yml")["handlers"]["journal_file_handler"]["base_dir"]
>>> num_files_before = len(list(Path(journal_path).iterdir()))
>>> session.run()
>>> assert len(list(Path(journal_path).iterdir())) == num_files_before
>>> context.run()
>>> assert len(list(Path(journal_path).iterdir())) == num_files_before + 1
```

## Expected Result
The first assert should fail and a file should be added. The second one works as expected.

## Actual Result
Both method should add an entry in the journal.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.17.3
* Python version used (`python -V`): Python 3.8.8
* Operating system and version: Ubuntu 20.04

**Comment by FlorianGD** [comment] 2021-04-29 13:54
Looking at the code of the 2 methods, they are very similar. But we have in `KedroContext.run()` (lines 635-639)
```python
        journal = Journal(record_data)

        catalog = self._get_catalog(
            save_version=save_version, journal=journal, load_versions=load_versions
        )
```
whereas in `KedroSession.run()` we have (lines 396-398)
```python
        catalog = context._get_catalog(
            save_version=save_version, load_versions=load_versions
        )
```
without the journal. Both sections are between the definition of `record_data` and the instantiation of the runner.

**Comment by MerelTheisenQB** [comment] 2021-04-30 08:55
Hi @FlorianGD, we are deprecating the `Journal` itself in Kedro 0.18.0, so that's why it wasn't included in the `KedroSession`. I realise we should have added the deprecation warning for the `Journal` earlier on, so apologies for that.

**Comment by MerelTheisenQB** [comment] 2021-05-17 15:10
I'm closing this issue as it's not a bug, but intentional functionality. The `Journal` will be deprecated in `0.18.0`.

**Closed by MerelTheisenQB** 2021-05-17 15:10 UTC
Labels: Issue: Bug Report

**Comment by selalamiTF** [comment] 2022-01-07 00:09
What is the alternative if we want to log the information in the journal ?

**Comment by MerelTheisenQB** [comment] 2022-01-07 09:29
Hi @selalamiTF! We'll be replacing most of the `Journal` functionality with [Kedro experiment tracking](https://kedro.readthedocs.io/en/stable/08_logging/02_experiment_tracking.html). This new feature is still in development so not all functionality has been released yet.
