### ISSUE TITLE
DataCatalog can't read in shapefile

### ISSUE THREAD

**Issue by DuongVu39** [quantumblacklabs/kedro#695] opened 2021-02-17 00:08 UTC
## Description
I can't read in shape files (shape file folder or .shp file) when specified them in conf/base/catalog.yml. If I import the GeoJSONDataSet, it works fine in a python script. Is it preferable to update the current implementation of GeoJSONDataSet or to create a new Extra Dataset Class for shape file?

## Context
I have a shapefolder containing .shp, .shx, .dbj, etc. file. I can feed the folder path to geopandas or GeoJSONDataSet to read in as a geojson dataframe but when I specify the path in the data catalog and run the node, it gives me an error

## Steps to Reproduce
1. This is what works:
```python
from kedro.extras.datasets.geopandas import GeoJSONDataSet
data = GeoJSONDataSet("sample_shape_file")
data
<kedro.extras.datasets.geopandas.geojson_dataset.GeoJSONDataSet at 0x1323e0dd0>

data_2 = GeoJSONDataSet("sample_shape_file/sample_shape_file.shp")
data_2
<kedro.extras.datasets.geopandas.geojson_dataset.GeoJSONDataSet at 0x1323f0950>
```

2. Here's what I have in my catalog.yml
```yml
shape_file_data:
  type: geopandas.GeoJSONDataSet
  filepath: data/01_raw/sample_shape_file
  save_args={'driver': GeoJSON}
```

3. Here's the node in my pipeline:
```python
node(
                func=do_something,
                inputs=[
                    "shape_file_data",
                    "params:location",
                ],
                outputs="filtered_shape_file_data",
                name="do_something",
            ),
```

4. When I run `kedro run --node=do_something`, I got this error:
```
2021-02-16 14:24:24,394 - root - INFO - ** Kedro project project_name
2021-02-16 14:24:24,434 - kedro.io.data_catalog - INFO - Loading data from `shape_file_data` (GeoJSONDataSet)...
2021-02-16 14:24:24,434 - kedro.runner.sequential_runner - WARNING - There are 1 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:

2021-02-16 14:24:24,442 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/io/core.py", line 208, in load
    return self._load()
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/extras/datasets/geopandas/geojson_dataset.py", line 149, in _load
    with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/fsspec/spec.py", line 936, in open
    **kwargs
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/fsspec/implementations/local.py", line 117, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/fsspec/implementations/local.py", line 199, in __init__
    self._open()
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/fsspec/implementations/local.py", line 204, in _open
    self.f = open(self.path, mode=self.mode)
IsADirectoryError: [Errno 21] Is a directory: '/Users/duongvu/project_name/data/01_raw/shape_file_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/duongvu/.pyenv/versions/env_name/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 696, in main
    cli_collection(**cli_context)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/duongvu/project_name/cli.py", line 212, in run
    pipeline_name=pipeline,
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/framework/session/session.py", line 414, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/runner/runner.py", line 100, in run
    self._run(pipeline, catalog, run_id)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/runner/sequential_runner.py", line 90, in _run
    run_node(node, catalog, self._is_async, run_id)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/runner/runner.py", line 212, in run_node
    node = _run_node_sequential(node, catalog, run_id)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/runner/runner.py", line 285, in _run_node_sequential
    inputs[name] = catalog.load(name)
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/io/data_catalog.py", line 402, in load
    result = func()
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/io/core.py", line 611, in load
    return super().load()
  File "/Users/duongvu/.pyenv/versions/3.7.7/envs/env_name/lib/python3.7/site-packages/kedro/io/core.py", line 217, in load
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while loading data from data set GeoJSONDataSet(filepath=/Users/duongvu/project_name/data/01_raw/shape_file_data, load_args={}, protocol=file, save_args={'driver': GeoJSON}).
[Errno 21] Is a directory: '/Users/duongvu/project_name/data/01_raw/shape_file_data'
```

5. If I specify the .shp file inside like this:
```yml
shape_file_data:
  type: geopandas.GeoJSONDataSet
  filepath: data/01_raw/sample_shape_file/sample_shape_file.shp
  save_args={'driver': GeoJSON}
```
I also got another error of: 
```
kedro.io.core.DataSetError: Failed while loading data from data set GeoJSONDataSet(...) not recognized as a supported file format.
```

6. I did try different save_args from "ESRI Shapefile" to None to "GeoJSON". None works.

## My Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used: 0.17.0
* Python version used: 3.7.7
* Operating system and version: MacOS

**Comment by mzjp2** [comment] 2021-02-17 03:00
> 1. This is what works:
> ```python
> from kedro.extras.datasets.geopandas import GeoJSONDataSet
> data = GeoJSONDataSet("sample_shape_file")
> data
> <kedro.extras.datasets.geopandas.geojson_dataset.GeoJSONDataSet at 0x1323e0dd0>
> 
> data_2 = GeoJSONDataSet("sample_shape_file/sample_shape_file.shp")
> data_2
> <kedro.extras.datasets.geopandas.geojson_dataset.GeoJSONDataSet at 0x1323f0950>
> ```

Can you run `data.load()` and `data_2.load()`? I suspect both will fail with the same errors you're seeing in your `kedro run` logs. The model here is that `data = GeoJSONDataSet(...)` is simply instantiating the dataset class with the various parameters, but it's _not_ actually trying to load the data yet using `GeoJSON`

The `kedro run` is both registering the dataset _and_ calling the `.load()` method on it to actually tell the dataset to load the data - the second step is what's failing. I'm not too well versed in `GeoJSON`, so I can't tell you _why_ it's failing right now, but thought I'd throw in the explanation for why it seems like your method 1 "works" whilst, 2 doesn't.

I suspect this points towards a mismatch of your data format with `GeoJSON`, rather than anything `kedro` specific.

**Comment by mzjp2** [comment] 2021-02-17 03:17
Building off the above, can you confirm that you get the same exception when trying to do:

```python
import geopandas as gpd

gpd.read_file("sample_shape_file/sample_shape_file.shp")
```

Assuming yes, I had a look at the [`geopandas` documentation](https://geopandas.org/reference/geopandas.read_file.html#geopandas.read_file) which says that the `read_file` is more or less proxied to [`fiona.open`](https://fiona.readthedocs.io/en/latest/fiona.html#fiona.open).

The documentation there re: drivers might be useful.

That said, I _think_ the crux of your problem is that you are specifying your driver options in `save_args`, when they should be provided in `load_args` - since the error seems to be occurring at the `load`ing stage of your node.

Can you try:

```yaml
# try this
shape_file_data:
  type: geopandas.GeoJSONDataSet
  filepath: data/01_raw/sample_shape_file/sample_shape_file.shp
  load_args:
    driver: "GeoJSON"

# or this
shape_file_data:
  type: geopandas.GeoJSONDataSet
  filepath: data/01_raw/sample_shape_file/sample_shape_file.shp
  load_args:
    driver: "ESRI Shapefile"
```

and let me know if that works? 🤞

**Comment by DuongVu39** [comment] 2021-02-17 04:06
Thank you for the quick reply. Yes, when I run `data.load()` and `data_2.load()`, it gave me the same error, so it doesn't actually work.

When I did 
```python
import geopandas as gpd

gpd.read_file("sample_shape_file/sample_shape_file.shp")
```
It works fine. This is how I read this file right now (passing the path in using parameters.yml and using geopandas to read the file in inside the node).

I did try the load_args for both "GeoJSON" and "ESRI Shapefile" and they both gave me the same error.

**Comment by mzjp2** [comment] 2021-02-17 04:14
Thanks for the reply, that’s hugely helpful in narrowing things down.

I wonder if it’s an encoding/mode thing. Can you try specifying:

```yaml
shape_file_data:
  type: geopandas.GeoJSONDataSet
  filepath: data/01_raw/sample_shape_file/sample_shape_file.shp
  fs_args:
    open_args_load:
      mode: rb
      encoding: maybe try this too?
```

otherwise I’ll need to try and get my hand on a `.shp` file to try and reproduce on my end.

**Comment by DuongVu39** [comment] 2021-02-17 16:19
Hi Zain, I did try putting either "GeoJSON" or "ESRI Shapefile" in the encoding with either the folder or the .shp file only and it still gives me the same error.

**Comment by mzjp2** [comment] 2021-02-17 16:37
Ah, the problem seems to stem from the fact that `fiona` (which is what `geoapandas` uses) doesn't want to read a _file handle_ - which is what Kedro passes down to `geopandas`. I can reproduce without Kedro using:

```python
with open("data/01_raw/shapefiles_dresden/gis_osm_pois_07_1.shp", "rb") as f:
    gpd.read_file(f)
```

which spits out:

```python-traceback
DriverError: '/vsimem/37bc3a0072fb487da73b368302b8960e/37bc3a0072fb487da73b368302b8960e' not recognized as a supported file format.
```

A hacky fix to this is to create your own `GeoJSONDataSet` (by inheriting from it) and replace the `load` method with your own, the only difference being that instead of passing the file handle down to `geopandas`, you pass down the filepath itself.

That said, I'm going to dig into this a litte, since https://github.com/Toblerity/Fiona/issues/409 says they do support file handles (as does the geopandas documentation)🤔

**Comment by mzjp2** [comment] 2021-02-17 17:18
Okay, so after reading some `geopandas` code - they (seemingly) fixed this issue in this PR https://github.com/geopandas/geopandas/pull/1535 which hasn't made its way into an official `geopandas` release yet. That said, I tried installing `geopandas` from the `master` source code, but run into the same error. It looks like a Fiona error :/

**Comment by DuongVu39** [comment] 2021-02-17 18:35
Oh yeah Fiona has a lot of problems. Thank you for looking into it. I can update the GeoJSONDataSet load method. Wonder if QB would prefer to have a ExtraDataSet for shape file or modify the current GeoJSONDataSet in the future?

**Comment by mzjp2** [comment] 2021-02-17 18:46
> Oh yeah Fiona has a lot of problems. Thank you for looking into it. I can update the GeoJSONDataSet load method. Wonder if QB would prefer to have a ExtraDataSet for shape file or modify the current GeoJSONDataSet in the future?

I'm not sure either. I think the right thing to do here is to raise this on `geopandas` (or maybe straight to `fiona`) and leave it with them to figure it out. In the meantime... 😬 

@limdauto tagging you in here for what the Kedro team would like to do.

**Comment by lorenabalan** [comment] 2021-04-19 09:16
Hi @DuongVu39 thank you for bringing this to our attention! @mzjp2 did a great job explaining the root cause & a workable alternative. Kedro relies on `fsspec` so we can graciously handle different filesystems (not just local), and looking at `geopandas` docs, they should be able to support this. Even trying out their docs fsspec snippet (in this [section](https://geopandas.org/docs/user_guide/io.html#reading-spatial-data)) I was getting the same error - but maybe it's worth you double-checking that as well with the latest version.

Given it's likely a bug on their side, I'd like to leave it with them to fix, so we don't introduce tech debt into our codebase. Please feel free to raise an issue on their repo, if there's no open one already, and link it here. 😊

**Comment by lorenabalan** [comment] 2021-04-21 14:10
Closing this as it's likely a bug on `geopandas` side. 
![Screenshot 2021-04-21 at 15 10 14](https://user-images.githubusercontent.com/6642900/115567939-b259b000-a2b3-11eb-989d-5974acca451f.png)

**Closed by lorenabalan** 2021-04-21 14:10 UTC
Labels: Issue: Bug Report

**Comment by Xabitsuki** [comment] 2021-11-19 10:35
From Geopandas documentation ([link](https://geopandas.org/en/stable/docs/user_guide/io.html#)) there should be an easy solution:
* instead of passing a path to the to `.shp` file
* Zip all the files in folder: `.shp`, `.shx`, `.dbf`, `.prj` etc in a folder
* use the folder path instead of the file path

Their example: 
```python
path = "simplecache::http://download.geofabrik.de/antarctica-latest-free.shp.zip"
with fsspec.open(path) as file:
    df = geopandas.read_file(file)
```

I have not test yet using the catalog but it should work but using this snippet with one of my files works.

**Comment by rabiahmad** [comment] 2022-06-18 23:31
> From Geopandas documentation ([link](https://geopandas.org/en/stable/docs/user_guide/io.html#)) there should be an easy solution:
> 
>     * Instead of passing a path to the to `.shp` file
> 
>     * Zip all the files together (inside a folder): `.shp`, `.shx`, `.dbf`, `.prj` etc.
> 
>     * Use the zip path instead of the `.shp` file path.
> 
> 
> Their example:
> 
> ```python
> path = "simplecache::http://download.geofabrik.de/antarctica-latest-free.shp.zip"
> with fsspec.open(path) as file:
>     df = geopandas.read_file(file)
> ```
> 
> ~I have not test yet using the catalog but it should work but using this snippet with one of my files works.~
> 
> It works.

I am also experiencing the same issues as others.
- I have tried putting a bunch of .shp files into a .zip folder.
- I referenced the zipped folder in `catalog.yml` as a type `PartitionedDataSet` and dataset `geopandas.GeoJSONDataSet`.
- When running the Kedro pipeline, it throws an error:
`DataSetError: Failed while loading data from data set GeoJSONDataSet (.....) 
'/vsizip//vsimem/044104f7a2f44a6195db133a30160744.zip' not recognized as a supported file format.`
- I can load the file using `geopandas.read_file()`. Just doesn't work through Kedro's load function.

If it's an issue with Fiona, does anyone know if this has been raised with somewhere?

**Comment by jamespolly** [comment] 2022-07-18 20:44
@rabiahmad I've shared your issue and had success by following the suggestion offered by @mzjp2. You should get the same results by following [these instructions for creating custom datasets](https://kedro.readthedocs.io/en/stable/extend_kedro/custom_datasets.html) and using the below code snippet for your definition file.

```
import logging
from copy import deepcopy
from io import BytesIO
from pathlib import PurePosixPath
from typing import Any, Dict, Union

import fsspec
import geopandas as gpd

from kedro.extras.datasets.geopandas.geojson_dataset import GeoJSONDataSet
from kedro.io.core import (
    PROTOCOL_DELIMITER,
    DataSetError,
    Version,
    get_filepath_str,
    get_protocol_and_path,
)

logger = logging.getLogger(__name__)


class ShapefileDataSet(GeoJSONDataSet):
    """``ShapefileDataSet`` loads/saves data to a GeoJSON file using an underlying filesystem
    (eg: local, S3, GCS). Inherited from GeoJSONDataSet with only modified load function.
    The underlying functionality is supported by geopandas, so it supports all
    allowed geopandas (pandas) options for loading and saving GeoJSON files.

    Example:
    ::

        >>> import geopandas as gpd
        >>> from kedro.extras.datasets.geopandas import ShapefileDataSet
        >>>
        >>> data = gpd.read_file('test.shp')
        >>>
        >>> data_set = ShapefileDataSet(filepath="test.shp")
        >>> data_set.save(data)
        >>> reloaded = data_set.load()
        >>>
        >>> assert data.equals(reloaded)

    """
    def _load(self) -> Union[gpd.GeoDataFrame, Dict[str, gpd.GeoDataFrame]]:
        load_path = get_filepath_str(self._get_load_path(), self._protocol)
        with self._fs.open(load_path, **self._fs_open_args_load) as fs_file:
            # return gpd.read_file(fs_file, **self._load_args)
            return gpd.read_file(load_path, **self._load_args)

```
