### ISSUE TITLE
Save kedro pipeline image by pillow.ImageDataSet without manually launching kedro-viz server

### ISSUE THREAD

**Issue by Minyus** [quantumblacklabs/kedro#375] opened 2020-05-19 04:54 UTC
## Description
Currently we have to launch the `kedro-viz` server to see the visualized pipeline. 
It will be more convenient if we can save the pipeline image by simply setting in `catalog.yml` like this:

```yaml
_PIPELINE_IMAGE:
  type: pillow.ImageDataSet
  filepath: data/_pipeline_image.png
```

## Context
This issue is related to #56 (moved to https://github.com/quantumblacklabs/kedro-viz/issues/31), but perhaps a more convenient feature.

## Possible Implementation
Provide some of the visualization code in `kedro-viz` as a Kedro hook.

## Possible Alternatives
Port some of the visualization code in `kedro-viz` to KedroContext.

**Comment by lorenabalan** [comment] 2020-05-27 17:15
Hi @Minyus ! I'm a little apprehensive about using some magic in the catalog to get the pipeline visualisation. I wonder if there's a way to leverage @WaylonWalker 's [kedro-static-viz](https://pypi.org/project/kedro-static-viz/) plugin here?

**Comment by Minyus** [comment] 2020-05-28 14:38
Hi @WaylonWalker , what do you think about using `kedro-static-viz` in a Kedro hook?

**Comment by WaylonWalker** [comment] 2020-05-29 04:09
@Minyus You nearly read my mind, `kedro-static-viz == 0.3.0` is out now with this functionality.

It does not create an image as the Issue is requesting, but it creates a static site will the same look, feel, and interactivity of `kedro-viz`, without the need to keep the flask server running if you have a place to host static content.

**Comment by Minyus** [comment] 2020-05-29 04:58
@WaylonWalker  Awesome! I'll try it. Thanks!

**Comment by lorenabalan** [comment] 2020-06-30 13:50
Closing this as resolved, loving the collaboration here. 😊

**Closed by lorenabalan** 2020-06-30 13:50 UTC
Labels: Issue: Feature Request
