### ISSUE TITLE
Error: no such option: --params with Kedro run

### ISSUE THREAD

**Issue by sanjaymeena** [quantumblacklabs/kedro#295] opened 2020-03-18 03:21 UTC
## Description
I am trying to specify parameters at runtime with `kedro run` as per https://kedro.readthedocs.io/en/latest/04_user_guide/03_configuration.html#additional-configuration-environments 

I get following error : 
```
Usage: kedro run [OPTIONS]
Try "kedro run -h" for help.

Error: no such option: --params
```

## Steps to Reproduce
1. kedro run --params param_key1:value1,param_key2:2.0

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.8 , 0.15.5
* Python version used (`python -V`): 3.7.6
* Operating system and version: Ubuntu

**Comment by yetudada** [comment] 2020-03-18 09:25
Hi @sanjaymeena! Thanks for flagging this bug and I'm so sorry you've run into this error. Would it be possible for you to type out the run command that you tried to run?

**Comment by 921kiyo** [comment] 2020-03-18 09:29
Hi @sanjaymeena Could you please check if you have `--params` click option in `kedro_cli.py` in your project. You should see the same lines as https://github.com/quantumblacklabs/private-kedro/blob/develop/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L232-L235 for `run()`

**Comment by sanjaymeena** [comment] 2020-03-18 21:52
> Hi @sanjaymeena! Thanks for flagging this bug and I'm so sorry you've run into this error. Would it be possible for you to type out the run command that you tried to run?

Hello @yetudada , I tried to run following test command : 

```
kedro run --params  a:b
```

**Comment by sanjaymeena** [comment] 2020-03-18 21:54
> Hi @sanjaymeena Could you please check if you have `--params` click option in `kedro_cli.py` in your project. You should see the same lines as https://github.com/quantumblacklabs/private-kedro/blob/develop/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L232-L235 for `run()`

Hello @921kiyo That repo is private, i cannot access it. I did try to add click option in kedro_cli.py. I am not sure if i missed something.

**Comment by mzjp2** [comment] 2020-03-18 22:01
> > Hi @sanjaymeena Could you please check if you have `--params` click option in `kedro_cli.py` in your project. You should see the same lines as https://github.com/quantumblacklabs/private-kedro/blob/develop/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L232-L235 for `run()`
> 
> Hello @921kiyo That repo is private, i cannot access it. I did try to add click option in kedro_cli.py. I am not sure if i missed something.

Stepping in here, can you try this link: https://github.com/quantumblacklabs/kedro/blob/da5259614c8268900df8080540926c1401b4cd47/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L232-L235

What version of `kedro` was your project generated with? If it was generated by an older version of `kedro` (0.15.4 or earlier), then the `kedro_cli.py` file won't have the necessary click option. If you do want to add the click option, then you should try copy-and-pasting the `run` function in the above link, but the key line that needs to be updated is adding the `click.option` decorator and the `extra_params=extra_params` in `load_context` as show in the link above. :)

**Comment by sanjaymeena** [comment] 2020-03-19 01:03
> > > Hi @sanjaymeena Could you please check if you have `--params` click option in `kedro_cli.py` in your project. You should see the same lines as https://github.com/quantumblacklabs/private-kedro/blob/develop/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L232-L235 for `run()`
> > 
> > 
> > Hello @921kiyo That repo is private, i cannot access it. I did try to add click option in kedro_cli.py. I am not sure if i missed something.
> 
> Stepping in here, can you try this link:
> 
> https://github.com/quantumblacklabs/kedro/blob/da5259614c8268900df8080540926c1401b4cd47/kedro/template/%7B%7B%20cookiecutter.repo_name%20%7D%7D/kedro_cli.py#L232-L269
> 
> What version of `kedro` was your project generated with? If it was generated by an older version of `kedro` (0.15.4 or earlier), then the `kedro_cli.py` file won't have the necessary click option. If you do want to add the click option, then you should try copy-and-pasting the `run` function in the above link, but the key line that needs to be updated is adding the `click.option` decorator and the `extra_params=extra_params` in `load_context` as show in the link above. :)

Hello @mzjp2 , 

thanks a bunch! Passing parameters works for me now :)

**Comment by WaiMarn** [comment] 2020-03-19 06:50
Hello, I have the same issue as but I've checked that I have --params click option in kedro_cli.py in my project. However I do not see --params option when I try kedro run -h. I am using kedro==0.15.8, python==3.7.5 and windows os.

**Comment by mzjp2** [comment] 2020-03-19 11:40
> Hello, I have the same issue as but I've checked that I have --params click option in kedro_cli.py in my project. However I do not see --params option when I try kedro run -h. I am using kedro==0.15.8, python==3.7.5 and windows os.

Hi @WaiMarn,

That's very odd, could you write an exhaustive list of steps (create virtual env, new kedro project, etc...) to reproduce this issue?

The only thing I can think would be that you have an older version of `kedro` in your "base" environment (are you using `conda`?). What does `which kedro` show and does it correctly show that it lives inside your current virtualenv?

**Comment by WaiMarn** [comment] 2020-03-20 01:28
Hi @mzjp2, thank you for replying!
I am using conda virtual env. My base env does not have kedro so I think it lives inside my current virtual env. I've tried creating a new environment and install kedro in it, but I still have this error.

**Comment by mzjp2** [comment] 2020-03-26 17:59
> Hi @mzjp2, thank you for replying!
> I am using conda virtual env. My base env does not have kedro so I think it lives inside my current virtual env. I've tried creating a new environment and install kedro in it, but I still have this error. Could it be that when initiate the kedro project, it was using 0.15.4? But if this is the case, do i initiate the project again?

Hey @WaiMarn, sorry for the late reply.

Could you attach the output of `kedro --version` and list the steps required to reproduce this?

**Comment by WaiMarn** [comment] 2020-03-27 03:02
Hi @mzjp2,

Output of kedro --version `kedro, version 0.15.6`

 List the steps required to reproduce this:
1. Initiate kedro project using kedro 0.15.4
2. Upgrade kedro to 0.15.6 in the env.

**Comment by mzjp2** [comment] 2020-03-27 09:51
> Hi @mzjp2,
> 
> Output of `kedro --version`: `kedro, version 0.15.6`
> 
> List the steps required to reproduce this:
> 
> 1. Initiate kedro project using kedro 0.15.4
> 2. Upgrade kedro to 0.15.6 in the env.
> 
> or
> 
> 1. Initiate kedro project using kedro 0.15.4
> 2. Update requirements.txt to kedro==0.15.6
> 3. kedro install

Hi @WaiMarn, I believe that's the expected behaviour in that case. When you generate the kedro template with an old version of Kedro, the `kedro_cli.py` file doesn't have some of the newer features that come with newer versions of `kedro`. If you want to make use of the newer features (like passing in `--params`) then you should generate the template using `kedro>=0.15.5` (I believe) and use `kedro>=0.15.5`. Upgrading `kedro` doesn't upgrade an already-generated `kedro` template.

If you want a quick workaround, then you can follow my comment a few posts up where you manually copy-paste snippets from a new template to your existing, old template. Let me know if that makes sense!

**Comment by WaiMarn** [comment] 2020-03-30 04:50
Hi @mzjp2,

Thank you for clarifying, it makes sense now. However, I am unable to use the quick workaround.
When I type `kedro -h', this is the output:
`Usage: kedro [OPTIONS] COMMAND [ARGS]...

  Kedro is a CLI for creating and using Kedro projects For more information,
  type ``kedro info``.

  When inside a Kedro project (created with `kedro new`) commands from the
  project's `kedro_cli.py` file will also be available here.

  Visualize the pipeline using kedroviz.

  Command line tools for manipulating a Kedro project.

Options:
  -V, --version  Show version and exit
  -v, --verbose  See extensive logging and error stack traces.
  -h, --help     Show this message and exit.

Global commands from Kedro
Commands:
  docs  See the kedro API docs and introductory tutorial.
  info  Get more information about kedro.
  new   Create a new kedro project.

Global commands from Kedro-Viz
Commands:
  viz  Visualize the pipeline using kedroviz.

Project specific commands from "project_path"\kedro_cli.py    
Commands:
  activate-nbstripout  Install the nbstripout git hook to automatically...
  build-docs           Build the project documentation.
  build-reqs           Build the project dependency requirements.
  install              Install project dependencies from both...
  ipython              Open IPython with project specific variables loaded.
  jupyter              Open Jupyter Notebook / Lab with project specific...
  package              Package the project as a Python egg and wheel.
  run                  Run the pipeline.
  test                 Run the test suite.`

**Comment by mzjp2** [comment] 2020-03-30 10:16
Closing this now, since it seems to have been resolved. Thanks all!

**Closed by mzjp2** 2020-03-30 10:16 UTC
Labels: Issue: Bug Report
