### ISSUE TITLE
[KED-882] Jupyterlab naming collision using text file tooltips

### ISSUE THREAD

**Issue by marcusinthesky** [quantumblacklabs/kedro#58] opened 2019-07-16 17:51 UTC
## Description
When editing .py text files with an attached console using `kedro jupyter lab` the kernel used by the console will continually restart when trying to autocompletion and tooltips, during spaceflight tutorial.  This is because of the tutorial requiring creating an io module.  

## Context
I was trying to edit python text files and was wondering why the console attached to the file was constantly dying when I was trying to make use of tooltips (shift + tab).  Having read up on the issues I believe its because  

## Steps to Reproduce  
1. Run `kedro jupyter lab` (jupyterlab==1.0.2)  
2. Open a .py text file  
3. Open console by right-clicking  
4. Try getting a tooltip for any arbitrary function like `print()` usign shift+tab  

## Expected Result
Tell us what should happen.

## Actual Result
Tell us what happens instead.

```
`[I 19:34:54.854 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Fatal Python error: init_sys_streams: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007fd301fbe740 (most recent call first):
```

```
[W 19:34:57.874 LabApp] KernelRestarter: restart failed
```

```
[W 19:34:57.875 LabApp] Kernel c1a79a1c-6ec1-44fb-b5c4-f18e6156ee19 died, removing from map.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): v0.14.3
* Python version used (`python -V`): 3.7.3
* Operating system and version: Ubuntu 18.04
* conda version: conda version : 4.6.14
* jupyterlab version: 1.0.2 installed from conda-forge (conda install -c conda-forge jupyterlab==1.0.2)

**Comment by yetudada** [comment] 2019-07-18 22:48
@marcusinthesky Firstly, I'm super amped that you're at UCT 🇿🇦!

Secondly, I've placed this bug report onto our backlog to get addressed. In the meanwhile, you can check out a completed version of the tutorial project in [`kedro-examples`](https://github.com/quantumblacklabs/kedro-examples). 

And, thirdly, you should also check out [`kedro-viz`](https://github.com/quantumblacklabs/kedro-viz) and visualise the pipeline when you're ready.

**Comment by Flid** [comment] 2019-07-29 12:31
Hi @marcusinthesky! I'm trying to reproduce the issue, no luck so far. But it really looks like the conflict between the original `io` module and something in kedro or your project.
I can do just
```bash
touch io.py
kedro jupyter lab```
And it fails to start with the same error.

Can you please check your code, is there a module called `io` anywhere?

What does `python -c 'import io; print(io.__file__)'` print?

**Comment by lorenabalan** [comment] 2019-08-06 13:52
I've updated the PR title with our internal ticket number to keep track of this more easily. :)

**Comment by 921kiyo** [comment] 2019-08-09 10:14
@marcusinthesky It is likely that global `io` variable in ipython config file was causing the problem, which we deleted in https://github.com/quantumblacklabs/kedro/commit/571bb8009b930e67c073115c23ae2d03942f6499#diff-5e39d56e37d29581584e70f13c8c607fL14 with the replacement of `context` variable. I am closing this issue for now, but feel free to re-open it if you are still having the problem.

**Closed by 921kiyo** 2019-08-09 10:14 UTC
Labels: Issue: Bug Report, Status: Approved
