### ISSUE TITLE
Command build-reqs and git repository dependencies inside custom wheel package

### ISSUE THREAD

**Issue by pedro-ricardo** [quantumblacklabs/kedro#877] opened 2021-09-06 23:25 UTC
## Description
When using the `kedro build-reqs` and having a git repository dependency inside a custom wheel package, it detects conflicts where they don't exist.

## Context
We heave a custom python library that depends on a git repository like `git+git://github.com/some/repo@some-commit` we use this because this repo has a bug in the dependencies of it's latest release that was fixed in the master branch, but not released just yet.
Upon building the wheel package of our library `pip install -r src/requirements.in` works like a charm. But when asking for the `kedro build-reqs` to analyse it, fake dependency conflicts happen.

## Steps to Reproduce
1. Create a virtual environment and add `pip3 install kedro` to it.
2. In a blank kedro root, add the following lines to `src/requirements.in`
    ```
    tsfresh
    protobuf>=3.12.0
    git+git://github.com/matrix-profile-foundation/matrixprofile@6bea7d4445
    ```
3. Run `kedro build-reqs` and `kedro install` to see that **it works**
4. Deactivate and Delete the virtual environment and re-create it, this time adding `pip3 install kedro poetry`
5. Create a fake package with poetry: `poetry new my_package`
6. Go to the new package folder: `cd my_package`
7. Add the following lines to `pyproject.toml` :
    ```
    [tool.poetry.dependencies]
    python = "^3.8"
    tsfresh = "*"
    protobuf = ">=3.12.0"
    matrixprofile = { git = "https://github.com/matrix-profile-foundation/matrixprofile.git", rev = "6bea7d4445" }
    ```
8. Create the package: `poetry build`
9. Copy the wheel package into kedro root folder: `cp dist/my_package-0.1.0-py3-none-any.whl ../.`
10. Go back to Kedro root: `cd ..`
11. Clean the `src/requirements.in` and add the package alone `my_package-0.1.0-py3-none-any.whl`
12. Run `kedro build-reqs`
13. Watch it take some time and give up on a dependency problem that does not exist. **Error 1**
14. Add `git+git://github.com/matrix-profile-foundation/matrixprofile@6bea7d4445` back to the `src/requirements.in` along with the custom package.
15. Run `kedro build-reqs`
16. Run `kedro install`
17. Watch for an even weirder result **Error 2**

## Expected Result
Correct generation of `requirements.txt` to install afterwards

## Actual Result
**Error 1:** In step **13** was:
```
Could not find a version that matches protobuf==3.11.2,>=3.12.0 (from matrixprofile==1.1.10->tsfresh==0.18.0->my-package==0.1.0->-r src/requirements.in (line 1))
( ... ) 
There are incompatible versions in the resolved dependencies:
  protobuf==3.11.2 (from matrixprofile==1.1.10->tsfresh==0.18.0->my-package==0.1.0->-r src/requirements.in (line 1))
  protobuf>=3.12.0 (from my-package==0.1.0->-r src/requirements.in (line 1))
```

**Error 2:** In step **17** was:
```
ERROR: Cannot install -r src/requirements.txt (line 52) and matrixprofile 1.1.10 (from git+git://github.com/matrix-profile-foundation/matrixprofile@6bea7d4445) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested matrixprofile 1.1.10 (from git+git://github.com/matrix-profile-foundation/matrixprofile@6bea7d4445)
    my-package 0.1.0 depends on matrixprofile 1.1.10 (from git+https://github.com/matrix-profile-foundation/matrixprofile.git@6bea7d4445)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

## Your Environment
Clean python 3.8 virtual environment with additional `pip3 install poetry kedro`

* kedro, version 0.17.4
* Python 3.8.11
* openSUSE Tumbleweed

**Comment by AntonyMilneQB** [comment] 2021-09-07 15:46
Thanks for the very thorough bug report! I've tried this out and decided it's not a kedro bug but rather some problem with poetry or piptools (and I suspect the latter). Note that `kedro build-reqs` is just a thin wrapper around pip-compile.

What seems to be happening here is that the specification `matrixprofile = { git = "https://github.com/matrix-profile-foundation/matrixprofile.git", rev = "6bea7d4445" }` from step 7 is not being picked up in step 13. In step 13 piptools is still trying to install `matrixprofile==1.1.10`, which [has pinned `protobuf==3.11.2`](https://github.com/matrix-profile-foundation/matrixprofile/blob/v1.1.10/setup.py#L71). This directly conflicts with the specification `protobuf = ">=3.12.0"`, hence the error message 1.

In step 17, it seems that again piptools is a bit confused about resolving the git dependency of matrixprofile. Notice that one of them is looking for `git+git://` and one is looking for `git+https://`, and it's clearly not resolving these to the same thing.

As to where the problem is, I'm not exactly sure. But if you examine the the METADATA in the .whl file generated by poetry, there's this line:
```Requires-Dist: matrixprofile @ git+https://github.com/matrix-profile-foundation/matrixprofile.git@6bea7d4445```
which looks good to me. Hence I think it *may* be a problem with piptools and I would suggest bringing this up with them first.

As for short term fixes, I would suggest:
* play around with `git+git://` compared to `git+https://`
* download master branch of matrixprofile and make your own local .whl file for it and specify that as a requirement
* specify the matrixprofile requirement in requirements.in *only* (others can stay in poetry if you like)

**Comment by AntonyMilneQB** [comment] 2021-09-07 15:48
Since this isn't actually a kedro issue I'm going to close it, but thank you for the report 🙂  Good luck with it!

**Closed by AntonyMilneQB** 2021-09-07 15:48 UTC
Labels: Issue: Bug Report
