### ISSUE TITLE
[KED-1456] Docker environment for developers

### ISSUE THREAD

**Issue by neomatrix369** [quantumblacklabs/kedro#265] opened 2020-02-26 22:43 UTC
## Description

I had issues building and running `kedro` tests on my MacOSX environment. Haven't had these conflicts in dependencies when working with other projects or packages. It's possible it's an isolated case but there is a chance it might happen to someone else's development environment.

## Context

Instead of immediately trying to debug this issue, I decided to create a docker environment for development and testing purposes. It takes care of managing python dependencies without conflicting with your host machine local environment python environments. It's also a good alternative way to run kedro (with or without our changes) in an isolated environment for sanity checking.

You run the shell script to start the docker environment, it has the relevant mappings to the python dependencies (isolated) environment and the `kedro` sources.

(Happy to share these scripts via a PR, if there isn't one already out there)

**Comment by ZainPatelQB** [comment] 2020-02-26 22:45
Is this related to/a duplicate of: https://github.com/quantumblacklabs/kedro/issues/254? :)

**Comment by neomatrix369** [comment] 2020-02-26 22:56
> Is this related to/a duplicate of: #254? :)

It's going to have additional functionality than just running tests in the docker environement.

You get a prompt inside the docker container where you can run all your commands from etc..

**Comment by neomatrix369** [comment] 2020-02-28 15:48
@ZainPatelQB I now have a PR - so you can see how this will be different from #254 - although both should persist

**Comment by neomatrix369** [comment] 2020-04-15 18:49
I did read that there is some work going on wrt Kedro docker, happy to align with that work if its available in the open. I have some experience in this area and happy to share it with this project.

**Comment by mzjp2** [comment] 2020-05-18 14:04
As mentioned in PR https://github.com/quantumblacklabs/kedro/pull/268

> Hey!
> 
> Thanks for raising this PR and sorry for the delay in getting back to you. We've had an internal discussion about this and decided that we'd instead focus on making the development requirements more minimal, rather than introducing a docker image. You can now run tests and get started on contributing without Spark installed, which was a major impediment before.
> 
> I'll go ahead and close this, but thank you again for the PR and discussion. :)

**Closed by mzjp2** 2020-05-18 14:04 UTC
Labels: Issue: Feature Request

**Comment by neomatrix369** [comment] 2020-06-07 06:20
> As mentioned in PR #268
> 
> > Hey!
> > Thanks for raising this PR and sorry for the delay in getting back to you. We've had an internal discussion about this and decided that we'd instead focus on making the development requirements more minimal, rather than introducing a docker image. You can now run tests and get started on contributing without Spark installed, which was a major impediment before.
> > I'll go ahead and close this, but thank you again for the PR and discussion. :)

So this does not solve the problem, it only pushes it into another direction and encapsulates it.

As a developer, I would still like to build and run the whole test suite. Also, docker gives great isolation and also easy to share images and build on top of it. As we know in the world of python each one of us has our own environments and wouldn't change it for another tool/package.

When one has errors or issues, it could be so many reasons, while docker would bring a standard way to reproduce it and fix it. I see more uses, advantages and pluses having it than not. But the final decision is of course yours.
